### ISSUE TITLE
auth0 Ruby on Rails TCP Error

### ISSUE THREAD

**Issue by cxk280** [auth0-samples/auth0-rubyonrails-api-samples#20]
I am using this repo as boilerplate to set up authentication with a new app. Everything is working up to but not including the "Test Your API with cURL" step on [the second page of the instructions](https://auth0.com/docs/quickstart/backend/rails/02-using).

I have tried testing both with cURL and with Postman, and both times I receive the following error:

`Errno::ECONNREFUSED in PrivateController#private. Failed to open TCP connection to :443 (Connection refused - connect(2) for nil port 443)`

The highlighted line of the error is the following: `jwks_raw = Net::HTTP.get URI("https://#{Rails.application.secrets.auth0_domain}/.well-known/jwks.json")`.

I receive the same error when I clone the sample repo directly and attempt testing with my Access Token, so it seems that it is possibly an oversight or outdated code in the example rather than some error with my incorporation of it into my own app.

I contacted auth0 support, and they told me to post the issue here. They said the engineering team had been alerted to the problem.

How do I resolve this?

**Comment by aaguiarz** [comment]
Did you set the domain/audience in your .env file as described in the Readme?

 # .env file
AUTH0_DOMAIN="myAuth0Domain"
AUTH0_AUDIENCE=myAPIAudience

If you download the Quickstart from the website https://auth0.com/docs/quickstart/backend/rails/01-authorization, while logged in, you should have those values set up.

**Comment by cxk280** [comment]
Ok, the example repo does work now when I do that. Please note that when following the directions on the walkthrough, the environmental variable issue is never mentioned. I cloned from the repo from Github, so they weren't automatically populated in as they are when you download the .zip file.

I still can't get my own repo to work, though. I've install the `dotenv` gem. My .env file is exactly the same as the one in the example repo that works. I updated `config/secrets.yml` to include the `auth0_domain` and `auth0_api_audience` variables as they exist in the example repo. The `lib/json_web_token.rb` file is exactly the same. What else could it be?

**Comment by mrrobby** [comment]
@cxk280, try removing the `#{}` around your secrets call, like:
```
jwks_raw = Net::HTTP.get URI(Rails.application.secrets.auth0_rsa_domain)
```
In your `.env` file, something like:
```
AUTH0_RSA_DOMAIN=https://<your-tenant>.auth0.com/.well-known/jwks.json
```

then in your `secrets.yml`, have something like:
```
development:
    secret_key_base: <stuff>
     .
     .
    auth0_rsa_domain: <%= ENV["AUTH0_RSA_DOMAIN"] %>
```
That way you can set your environment on the server.  Do not check in your `.env` file.
Do the exact same thing for your base domain and your audience.

It would also be worth noting that we should move this example to enable caching of the `jwks_raw` url.

Hope this works!

**Comment by cxk280** [comment]
I followed @mrrobby 's instructions, and it's still not working. The error changed, though:

`SocketError (Failed to open TCP connection to Rails.application.secrets.auth0_domain:443 (getaddrinfo: nodename nor servname provided, or not known)):
  
lib/json_web_token.rb:19:in `jwks_hash'
lib/json_web_token.rb:14:in `block in verify'
lib/json_web_token.rb:7:in `verify'
app/controllers/concerns/secured.rb:31:in `auth_token'
app/controllers/concerns/secured.rb:17:in `authenticate_request!'`

Does this shine any more light on it?

Also, it is not clear to me the purpose of the `AUTH0_RSA_DOMAIN` variable. I added it in `.env` and `config/secrets.yml` as instructed, but doesn't it need to be used somewhere? Did you intend this as a replacement for the `AUTH0_DOMAIN` variable used in the example?

**Comment by cxk280** [comment]
After following @mrrobby 's suggestions, I receive a different error:

```
ArgumentError (bad argument (expected URI object or URI string)):
  
lib/json_web_token.rb:20:in `jwks_hash'
lib/json_web_token.rb:15:in `block in verify'
lib/json_web_token.rb:7:in `verify'
app/controllers/concerns/secured.rb:31:in `auth_token'
app/controllers/concerns/secured.rb:17:in `authenticate_request!'
```

Any idea what to do?

**Comment by mrrobby** [comment]
@cxk280 can you post some of your code (and obfuscate entries in secrets) and what you've done to debug so we can help you solve what's wrong?

The error you've posted reflects a possibility that your `Rails.application.secrets` ref is not being parsed properly, but that should be pretty simple to fix if we can see what you've done.

**Comment by alexisluque** [comment]
@cxk280, when you download the `.zip`, `AUTH0_DOMAIN` is setup, but you need to set the identifier of you API in ´AUTH0_AUDIENCE´.

**Comment by cxk280** [comment]
@alexisluque I did that, but I'm still getting the same error.

@mrrobby , see some of my relevant code below with sensitive info obfuscated:

**.env**:

```
AUTH0_DOMAIN=https://<domain>.auth0.com/
AUTH0_API_AUDIENCE=http://localhost:3001/api
AUTH0_RSA_DOMAIN=https://<domain>.auth0.com/.well-known/jwks.json
```

**lib/json_web_token.rb**:

```
# frozen_string_literal: true
require 'net/http'
require 'uri'

class JsonWebToken
  def self.verify(token)
    JWT.decode(token, nil,
               true, # Verify the signature of this token
               algorithm: 'RS256',
               # iss: "https://#{Rails.application.secrets.auth0_domain}/",
               iss: Rails.application.secrets.auth0_domain,
               verify_iss: true,
               aud: Rails.application.secrets.auth0_api_audience,
               verify_aud: true) do |header|
      jwks_hash[header['kid']]
    end
  end

  def self.jwks_hash
    jwks_raw = Net::HTTP.get URI(Rails.application.secrets.auth0_rsa_domain)
    jwks_keys = Array(JSON.parse(jwks_raw)['keys'])
    Hash[
      jwks_keys
      .map do |k|
        [
          k['kid'],
          OpenSSL::X509::Certificate.new(
            Base64.decode64(k['x5c'].first)
          ).public_key
        ]
      end
    ]
  end
end
```

**config/secrets.html**:

```
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: <stuff>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: <stuff>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
  auth0_rsa_domain: <%= ENV["AUTH0_RSA_DOMAIN"] %>

test:
  secret_key_base: <stuff>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
  auth0_rsa_domain: <%= ENV["AUTH0_RSA_DOMAIN"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
  auth0_rsa_domain: <%= ENV["AUTH0_RSA_DOMAIN"] %>
```
